"""Create work comp sisc table

Revision ID: c04d91e17ac9
Revises: 
Create Date: 2025-07-03 10:21:49.623492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04d91e17ac9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_comp_sisc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FROM_DATE', sa.String(), nullable=True),
    sa.Column('THROUGH_DATE', sa.String(), nullable=True),
    sa.Column('CHECK_NUMBER', sa.String(), nullable=True),
    sa.Column('CHECK_DATE', sa.String(), nullable=True),
    sa.Column('PAYEE', sa.String(), nullable=True),
    sa.Column('AMOUNT', sa.Float(), nullable=True),
    sa.Column('EMPLOYEE', sa.String(), nullable=True),
    sa.Column('CLAIM_NUMBER', sa.String(), nullable=True),
    sa.Column('SSN', sa.String(), nullable=True),
    sa.Column('EMPLID', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_comp_sisc')
    # ### end Alembic commands ###
